# Generated by Django 4.2.7 on 2023-11-18 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала рассылки')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания рассылки')),
                ('send_time', models.TimeField(verbose_name='Время длительности рассылки')),
                ('send_frequency', models.CharField(choices=[('daily', 'раз в день'), ('weekly', 'раз в неделю'), ('monthly', 'раз в месяц')], max_length=10, verbose_name='Частота рассылки')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('completed', 'Завершена')], default='created', max_length=15, verbose_name='Статус рассылки')),
                ('clients', models.ManyToManyField(related_name='mailings', to='clients.client', verbose_name='Клиенты')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='тема')),
                ('body', models.TextField(verbose_name='сообщение')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mail', verbose_name='рассылка')),
            ],
        ),
    ]
