# Generated by Django 4.2.7 on 2023-11-19 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='user',
            new_name='user_id',
        ),
    ]
