# Generated by Django 4.2.7 on 2023-11-20 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_rename_user_mail_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='user_id',
            new_name='user',
        ),
    ]
