# Generated by Django 4.2.7 on 2023-11-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_rename_user_id_mail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='title',
            field=models.CharField(default='Mail', max_length=100, verbose_name='Название рассылки'),
            preserve_default=False,
        ),
    ]
