# Generated by Django 4.2.7 on 2023-11-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_mail_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('completed', 'Завершена'), ('blocked', 'Заблокирована')], default='created', max_length=15, verbose_name='Статус рассылки'),
        ),
    ]
