# Generated by Django 4.2.7 on 2023-12-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_message_options_mail_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
    ]
