# Generated by Django 4.2.7 on 2023-12-02 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_mail_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mail', verbose_name='рассылка'),
        ),
    ]
